TradeTrust/tradetrust-config

README.md, build/config-sample-v3.json, fixtures/config/forms/v3/bill-of-lading.json, fixtures/config/forms/v3/coo-chafta.json, fixtures/config/forms/v3/invoice.json, package-lock.json, package.json, src/config-v2.schema.json, src/config-v3.schema.json, src/examples/config-file.ts, src/generate-config.ts
=> feat: build config v3

README.md, src/config-v2.schema.json, src/config-v3.schema.json
- missed out some properties on v2, v3 forms
=> fix: missing properties

.eslintrc.json, .github/workflows/manual.yml, README.md, build/config-sample-v2.json, build/config-sample-v3.json, fixtures/config/forms/v2/bill-of-lading.json, fixtures/config/forms/v2/coo-chafta.json, fixtures/config/forms/v2/cover-letter.json, fixtures/config/forms/v2/invoice.json, fixtures/config/forms/v3/bill-of-lading.json, fixtures/config/forms/v3/coo-chafta.json, fixtures/config/forms/v3/invoice.json, package-lock.json, package.json, src/generate-config.ts, src/helpers/helpers.ts
- update forms with constants
- add lint
=> feat: update forms

build/config-sample-v2.json, fixtures/config/forms/v2/coo-simple.json, src/config-v2.schema.json, src/helpers/helpers.ts
- fix incorrect did schema
- add simple coo
=> fix: did schema

build/config-sample-v2.json, build/config-sample-v3.json, fixtures/config/forms/v2/invoice-dns-did.json, src/config-v2.schema.json, src/examples/config-file.ts
=> feat: dns did form

src/examples/config-file.ts, src/examples/wallet.ts, src/generate-config.ts, src/helpers/helpers.ts, src/types/types.ts, src/utils/utils.ts, test/validate.test.ts
- add aws kms type and other typings
=> chore: types

.github/workflows/manual.yml, .gitignore, README.md, package-lock.json, package.json, src/config-v2.schema.json, src/config-v3.schema.json, src/examples/config-file.ts, src/examples/forms.ts, src/generate-config.ts, src/helpers/helpers.ts, src/types/types.ts, src/utils/utils.ts, typedoc.json
- type config with oa
- add typedocs
=> docs: generate typedocs

build/config-reference-v2.json, build/config-reference-v3.json, build/local/config-v2.json, build/local/config-v3.json, build/rinkeby/config-v2.json, build/rinkeby/config-v3.json, build/ropsten/config-v2.json, build/ropsten/config-v3.json, fixtures/config/forms/v2/coo-chafta.json, fixtures/config/forms/v2/coo-simple.json, fixtures/config/forms/v2/cover-letter.json, fixtures/config/forms/v2/invoice.json, fixtures/config/forms/v3/coo-chafta.json, fixtures/config/forms/v3/invoice-dns-did.json, src/examples/config-file.ts, src/helpers/helpers.ts
- add dns-did example (invoice v3)
- allow documentStorage
- add revocation none as default to all verifiable document examples
=> feat: add dns-did

.gitignore, README.md, netlify/functions/schema/index.ts, package-lock.json, package.json, test/schema.test.ts
- endpoint for config schema with netlify functions
=> feat: netlify functions

package-lock.json, package.json, src/helpers/helpers.ts
=> fix: refactor helper function to update the form  in config file

build/config-reference-v2.json, build/config-reference-v3.json, build/local/config-v2.json, build/local/config-v3.json, build/rinkeby/config-v2.json, build/rinkeby/config-v3.json, build/ropsten/config-v2.json, build/ropsten/config-v3.json, fixtures/config/forms/v2/bill-of-lading.json, fixtures/config/forms/v3/bill-of-lading.json, src/config-v2.schema.json, src/config-v3.schema.json, src/examples/config-file.ts
- revocation required, defaults to `NONE`
- [reference](https://github.com/Open-Attestation/adr/blob/master/issuing_using_did.md#for-documents-that-are-signed-directly)
=> fix: revocation required

.github/workflows/manual.yml, build/config-reference-v2.json, build/config-reference-v3.json, build/local/config-v2.json, build/local/config-v3.json, build/rinkeby/config-v2.json, build/rinkeby/config-v3.json, build/ropsten/config-v2.json, build/ropsten/config-v3.json, fixtures/config/forms/v2/bill-of-lading.json, fixtures/config/forms/v2/coo-chafta.json, fixtures/config/forms/v2/coo-simple.json, fixtures/config/forms/v2/cover-letter.json, fixtures/config/forms/v2/invoice-dns-did.json, fixtures/config/forms/v2/invoice.json, fixtures/config/forms/v3/bill-of-lading.json, fixtures/config/forms/v3/coo-chafta.json, fixtures/config/forms/v3/invoice-dns-did.json, fixtures/config/forms/v3/invoice.json, src/utils/utils.ts, test/validate.test.ts
- ajv passing in creator, even though data file is different from schema
- validate false if additional properties in data is detected
=> fix: additional properties

build/config-reference-v3.json, build/local/config-v3.json, build/rinkeby/config-v3.json, build/ropsten/config-v3.json, fixtures/config/forms/v3/bill-of-lading.json, fixtures/config/forms/v3/coo-chafta.json, fixtures/config/forms/v3/invoice-dns-did.json, fixtures/config/forms/v3/invoice.json, test/validate.test.ts
- `additionalProperties` set at wrong level
- add test for v3 docs
=> fix: v3 schema

build/config-reference-v3.json, build/local/config-v3.json, build/rinkeby/config-v3.json, build/ropsten/config-v3.json, fixtures/config/forms/v3/bill-of-lading.json, fixtures/config/forms/v3/coo-chafta.json, fixtures/config/forms/v3/invoice-dns-did.json, fixtures/config/forms/v3/invoice.json, test/validate.test.ts
related: https://github.com/TradeTrust/document-creator-website/pull/248
TODO: could extract each form schema out to reuse in v2, v3 configs
=> fix: remove credentialSubject

build/config-reference-v2.json, build/config-reference-v3.json, build/goerli/config-v2.json, build/goerli/config-v3.json, build/local/config-v2.json, build/local/config-v3.json, build/rinkeby/config-v2.json, build/rinkeby/config-v3.json, src/examples/config-file.ts
- update document storage endpoint url
=> fix: document storage

build/config-reference-v2.json, build/config-reference-v3.json, build/goerli/config-v2.json, build/goerli/config-v3.json, build/local/config-v2.json, build/local/config-v3.json, build/rinkeby/config-v2.json, build/rinkeby/config-v3.json, fixtures/config/forms/v2/coo-chafta.json, fixtures/config/forms/v2/coo-simple.json, fixtures/config/forms/v3/coo-chafta.json
- fix more ui schema not displaying the correct widget.
=> fix: more uischema template

build/goerli/config-v2.json, build/goerli/config-v3.json, build/local/config-v2.json, build/maticmum/config-v2.json, build/maticmum/config-v3.json, package-lock.json, package.json, src/generate-config.ts, src/helpers/helpers.ts, src/types/index.ts
- generate `network` in forms.
- generate maticmum config.
=> chore: generate form network

build/goerli/config-v2.json, build/goerli/config-v3.json, build/local/config-v2.json, build/local/config-v3.json, build/maticmum/config-v2.json, build/maticmum/config-v3.json, src/helpers/helpers.ts
- revert `network` first until creator validate is figured out
=> chore: revert network

package-lock.json, package.json, src/generate-config.ts, src/helpers/helpers.ts
- should validate against updated configs, rather than reference configs
=> chore: validate updated config

.github/workflows/manual.yml, build/goerli/config-v2.json, build/goerli/config-v3.json, build/local/config-v2.json, build/local/config-v3.json, build/maticmum/config-v2.json, build/maticmum/config-v3.json, src/config-v2.schema.json, src/config-v3.schema.json, src/examples/config-file.ts, src/helpers/helpers.ts, src/shared/updateForm.ts, test/updateForm.test.ts
- build config files with `network`
- update schema for network check
- `network` will be added in `updateForm` util
=> fix: update network

.github/workflows/manual.yml, README.md, src/generate-config.ts
- add more docs
- re-enable release
=> docs: more docs

build/maticmum/config-v2.json, build/maticmum/config-v3.json, build/sepolia/config-v2.json, build/sepolia/config-v3.json, fixtures/config/wallet/wallet-testnet.json, src/generate-config.ts
- wallet update missed out in https://github.com/TradeTrust/tradetrust-config/pull/53
- update to correct maticmum tk and doc store addresses
=> fix: update wallet

package-lock.json, package.json, src/constants.ts, src/generate-config.ts, test/dns.test.ts
- check if dns txt really does contain addresses, to ensure dnsprove will work
- making live calls to google dns though
=> test: dns txt

build/local/config-v2.json, build/maticmum/config-v2.json, build/reference/config-v2.json, build/sepolia/config-v2.json, fixtures/config/forms/v2/bill-of-lading-maersk-pilot.json, src/config-v2.schema.json
- add maersk pilot form, oa v2
- https://www.pivotaltracker.com/story/show/185745034
=> feat: form maersk pilot

build/local/config-v2.json, build/maticmum/config-v2.json, build/reference/config-v2.json, build/sepolia/config-v2.json, build/xdcapothem/config-v2.json, fixtures/config/forms/v2/warehouse-receipt.json, src/config-v2.schema.json
feat: tt-68-warehouse-receipt-template
=> feat: tt-68-warehouse-receipt-template

src/config-v2.schema.json, src/config-v3.schema.json
added mainnet and testnet hedera network configurations.
=> feat(added support for hedera network): krypc

build/stability/config-v2.json, build/stability/config-v3.json, package-lock.json, package.json, src/config-v2.schema.json, src/config-v3.schema.json, src/constants.ts
This PR adds support for [Stability GTN](https://github.com/stabilityprotocol/) network.
- constants
NA
=> feat: add stability chain configuration

README.md, typedoc.json
=> fix: update readme

build/amoy/config-v2.json, build/amoy/config-v3.json, build/hederatestnet/config-v2.json, build/stability/config-v2.json, build/stability/config-v3.json, package-lock.json, package.json, src/config-v2.schema.json, src/config-v3.schema.json, src/constants.ts, src/examples/config-file.ts, src/generate-config.ts, test/dns.test.ts
Add support for Polygon Amoy Testnet
=> feat: added support for amoy testnet

package-lock.json, package.json
update tradetrust util deps as the upstream dep dnsprove is updated
=> fix: update tt-util dep

.github/workflows/manual.yml, .releaserc, build/amoy/config-v4.json, build/hederatestnet/config-v4.json, build/local/config-v4.json, build/reference/config-v4.json, build/sepolia/config-v4.json, build/stability/config-v4.json, build/stabilitytestnet/config-v4.json, build/xdcapothem/config-v4.json, fixtures/config/forms/v4/bill-of-lading.json, fixtures/config/forms/v4/invoice.json, netlify/functions/schema/index.ts, package-lock.json, package.json, src/config-v4.schema.json, src/examples/config-file.ts, src/examples/forms.ts, src/generate-config.ts, src/helpers/helpers.ts, src/response.js, src/shared/updateForm.ts, src/types/index.ts, src/utils/utils.ts, test/schema.test.ts, test/updateForm.test.ts, test/validate.test.ts
=> feat: tradetrust v4

.github/workflows/manual.yml, build/astrontestnet/config-v2.json, build/astrontestnet/config-v3.json, package-lock.json, package.json, src/config-v2.schema.json, src/config-v3.schema.json, src/constants.ts, src/generate-config.ts, test/updateFormAstronTestnet.test.ts, test/validateAstronTestnet.test.ts
update astron testnet v5 configs and contracts
[JIRA TICKET](https://afa-cdi.atlassian.net/browse/TT-382?atlOrigin=eyJpIjoiNTU0ZDY4YzAzYmJkNGY5Yzg4NTNlNmQ5NGY3MTE0Y2QiLCJwIjoiaiJ9)
=> chore: update astron testnet v5 configs and contracts

build/astrontestnet/config-v2.json, build/astrontestnet/config-v3.json, src/constants.ts, test/dns.test.ts
update astron testnet token registry address
[Jira Ticket](https://afa-cdi.atlassian.net/browse/TT-382?atlOrigin=eyJpIjoiNTU0ZDY4YzAzYmJkNGY5Yzg4NTNlNmQ5NGY3MTE0Y2QiLCJwIjoiaiJ9)
=> chore: update astron testnet token registry address

build/astrontestnet/config-v2.json, build/astrontestnet/config-v3.json, src/constants.ts
Update v4 contracts with new owner - 0xCA93690Bb57EEaB273c796a9309246BC0FB93649
=> chore: update contract v4

build/astrontestnet/config-v2.json, build/astrontestnet/config-v3.json, src/constants.ts
Update contracts with owner - 0xCA93690Bb57EEaB273c796a9309246BC0FB93649
=> chore: update contracts
